const clientesDB = [
  {
    "id": "ACOSTA SERVICIOS SRL - 30718686217",
    "codigo": "7",
    "nombre": "ACOSTA SERVICIOS SRL",
    "cuit": "30718686217",
    "telefono": "",
    "email": "",
    "condicion_id": "0",
    "condicion_nombre": "NO USAR",
    "deposito_id": "0",
    "deposito_nombre": "Depósito 0",
    "transporte_id": "0",
    "transporte_nombre": "Transporte 0",
    "vendedor_id": "1",
    "vendedor_nombre": "",
    "estado": "ACTIVOS",
    "domicilio": "GARAY 1021",
    "localidad": "PUERTO GENERAL SAN MARTIN",
    "deuda_actual": 0.0,
    "facturas_mora": []
  },
  {
    "id": "CARGILL SACI - 30506792165",
    "codigo": "2",
    "nombre": "CARGILL SACI",
    "cuit": "30506792165",
    "telefono": "3415890126",
    "email": "8",
    "condicion_id": "2",
    "condicion_nombre": "30 Y 60 DIAS 50\\50",
    "deposito_id": "0",
    "deposito_nombre": "Depósito 0",
    "transporte_id": "0",
    "transporte_nombre": "Transporte 0",
    "vendedor_id": "1",
    "vendedor_nombre": "",
    "estado": "ACTIVOS",
    "domicilio": "YRIGOYEN Y PUNTA QUBRACHO",
    "localidad": "PUERTO GENERAL SAN MARTIN",
    "deuda_actual": 0.0,
    "facturas_mora": []
  },
  {
    "id": "CARGILL SACI - 30506792165",
    "codigo": "3",
    "nombre": "CARGILL SACI",
    "cuit": "30506792165",
    "telefono": "3413269645",
    "email": "9",
    "condicion_id": "2",
    "condicion_nombre": "30 Y 60 DIAS 50\\50",
    "deposito_id": "0",
    "deposito_nombre": "Depósito 0",
    "transporte_id": "0",
    "transporte_nombre": "Transporte 0",
    "vendedor_id": "1",
    "vendedor_nombre": "",
    "estado": "ACTIVOS",
    "domicilio": "SOLIS 822",
    "localidad": "VILLA GOBERNADOR GALVEZ",
    "deuda_actual": 0.0,
    "facturas_mora": []
  },
  {
    "id": "CARGILL SACI - 30506792165",
    "codigo": "4",
    "nombre": "CARGILL SACI",
    "cuit": "30506792165",
    "telefono": "",
    "email": "",
    "condicion_id": "3",
    "condicion_nombre": "30 DIAS",
    "deposito_id": "0",
    "deposito_nombre": "Depósito 0",
    "transporte_id": "0",
    "transporte_nombre": "Transporte 0",
    "vendedor_id": "1",
    "vendedor_nombre": "",
    "estado": "ACTIVOS",
    "domicilio": "LUIS RAUL MAZA 35",
    "localidad": "BERNARDO LARROUDE",
    "deuda_actual": 0.0,
    "facturas_mora": []
  },
  {
    "id": "CONSUMIDOR FINAL - 23402204",
    "codigo": "1",
    "nombre": "CONSUMIDOR FINAL",
    "cuit": "23402204",
    "telefono": "",
    "email": "",
    "condicion_id": "1",
    "condicion_nombre": "CONTADO",
    "deposito_id": "0",
    "deposito_nombre": "Depósito 0",
    "transporte_id": "0",
    "transporte_nombre": "Transporte 0",
    "vendedor_id": "1",
    "vendedor_nombre": "",
    "estado": "ACTIVOS",
    "domicilio": "",
    "localidad": "ROSARIO",
    "deuda_actual": 0.0,
    "facturas_mora": []
  },
  {
    "id": "JULIO ALVAREZ - 30716236990",
    "codigo": "5",
    "nombre": "JULIO ALVAREZ",
    "cuit": "30716236990",
    "telefono": "",
    "email": "",
    "condicion_id": "0",
    "condicion_nombre": "NO USAR",
    "deposito_id": "0",
    "deposito_nombre": "Depósito 0",
    "transporte_id": "0",
    "transporte_nombre": "Transporte 0",
    "vendedor_id": "1",
    "vendedor_nombre": "",
    "estado": "ACTIVOS",
    "domicilio": "BS AS 1122",
    "localidad": "PUERTO GENERAL SAN MARTIN",
    "deuda_actual": 0.0,
    "facturas_mora": []
  },
  {
    "id": "PV SERVICIOS SRL - 30716598205",
    "codigo": "10",
    "nombre": "PV SERVICIOS SRL",
    "cuit": "30716598205",
    "telefono": "",
    "email": "",
    "condicion_id": "0",
    "condicion_nombre": "NO USAR",
    "deposito_id": "0",
    "deposito_nombre": "Depósito 0",
    "transporte_id": "0",
    "transporte_nombre": "Transporte 0",
    "vendedor_id": "1",
    "vendedor_nombre": "",
    "estado": "ACTIVOS",
    "domicilio": "",
    "localidad": "",
    "deuda_actual": 0.0,
    "facturas_mora": []
  },
  {
    "id": "SAO CLIMA SRL - 30715472313",
    "codigo": "11",
    "nombre": "SAO CLIMA SRL",
    "cuit": "30715472313",
    "telefono": "",
    "email": "",
    "condicion_id": "0",
    "condicion_nombre": "NO USAR",
    "deposito_id": "0",
    "deposito_nombre": "Depósito 0",
    "transporte_id": "0",
    "transporte_nombre": "Transporte 0",
    "vendedor_id": "1",
    "vendedor_nombre": "",
    "estado": "ACTIVOS",
    "domicilio": "GRAL PAZ 344",
    "localidad": "CAPITAN BERMUDEZ",
    "deuda_actual": 0.0,
    "facturas_mora": []
  },
  {
    "id": "SILC SERVICIOS SRL - 30717824594",
    "codigo": "8",
    "nombre": "SILC SERVICIOS SRL",
    "cuit": "30717824594",
    "telefono": "",
    "email": "",
    "condicion_id": "0",
    "condicion_nombre": "NO USAR",
    "deposito_id": "0",
    "deposito_nombre": "Depósito 0",
    "transporte_id": "0",
    "transporte_nombre": "Transporte 0",
    "vendedor_id": "1",
    "vendedor_nombre": "",
    "estado": "ACTIVOS",
    "domicilio": "",
    "localidad": "",
    "deuda_actual": 0.0,
    "facturas_mora": []
  },
  {
    "id": "T6 INDUSTRIAL S.A - 33689206099",
    "codigo": "9",
    "nombre": "T6 INDUSTRIAL S.A",
    "cuit": "33689206099",
    "telefono": "",
    "email": "",
    "condicion_id": "0",
    "condicion_nombre": "NO USAR",
    "deposito_id": "0",
    "deposito_nombre": "Depósito 0",
    "transporte_id": "0",
    "transporte_nombre": "Transporte 0",
    "vendedor_id": "1",
    "vendedor_nombre": "",
    "estado": "ACTIVOS",
    "domicilio": "Hipolito Yrigoyen y Gral. Luci",
    "localidad": "PUERTO GENERAL SAN MARTIN",
    "deuda_actual": 0.0,
    "facturas_mora": []
  },
  {
    "id": "Terminal 6 s.a - 30615829699",
    "codigo": "6",
    "nombre": "Terminal 6 s.a",
    "cuit": "30615829699",
    "telefono": "",
    "email": "",
    "condicion_id": "0",
    "condicion_nombre": "NO USAR",
    "deposito_id": "0",
    "deposito_nombre": "Depósito 0",
    "transporte_id": "0",
    "transporte_nombre": "Transporte 0",
    "vendedor_id": "1",
    "vendedor_nombre": "",
    "estado": "ACTIVOS",
    "domicilio": "Hipolito Yrigoyen y Costa Del",
    "localidad": "PUERTO GENERAL SAN MARTIN",
    "deuda_actual": 0.0,
    "facturas_mora": []
  }
];
